services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 25565:25565
    volumes:
      - ${PWD}/world:/usr/local/reindev/world
      - ${PWD}/mods:/usr/local/reindev/mods
    environment:
      - JAVA_OPTS=-Xmx2G -Xms2G
      - FOXLOADER=${FOXLOADER:-0}
    restart: always

  backup:
    image: alpine
    volumes:
      - ${PWD}/world:/usr/local/reindev/world
      - ${PWD}/backups:/backups
      - ${PWD}/scripts/backup.sh:/backup.sh:ro
    entrypoint: ["/bin/sh"]
    command: -c "mkdir -p /backups && while true; do /backup.sh; sleep 4h; done"
    restart: always